branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode9.1
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - TEST_TYPE=ParseUI
    - TEST_TYPE=ParseUIDemo-ObjC
    - TEST_TYPE=ParseUIDemo-Swift
    - TEST_TYPE=CocoaPods
install:
- |
  gem install xcpretty --no-document -N
  gem install cocoapods --no-document --quiet
  pod repo update
  pod install
script:
- |
  if [ "$TEST_TYPE" = ParseUI ]; then
    set -o pipefail
    xcodebuild -workspace ParseUI.xcworkspace -scheme 'ParseUI' -sdk iphonesimulator build | xcpretty -c
  elif [ "$TEST_TYPE" = ParseUIDemo-ObjC ]; then
    set -o pipefail
    xcodebuild -workspace ParseUI.xcworkspace -scheme 'ParseUIDemo' -sdk iphonesimulator build | xcpretty -c
  elif [ "$TEST_TYPE" = ParseUIDemo-Swift ]; then
    set -o pipefail
    xcodebuild -workspace ParseUI.xcworkspace -scheme 'ParseUIDemo-Swift' -sdk iphonesimulator build | xcpretty -c
  elif [ "$TEST_TYPE" = CocoaPods ]; then
    pod lib lint ParseUI.podspec
    pod lib lint --use-libraries ParseUI.podspec    
  fi